# Generated by Django 5.0.4 on 2024-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvs_app', '0003_broadcastinginfo_viewers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastinginfo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
