# Generated by Django 5.0.4 on 2024-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvs_app', '0005_servertimezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastinginfo',
            name='video_file',
        ),
        migrations.AddField(
            model_name='broadcastinginfo',
            name='video_id',
            field=models.CharField(default='0V', max_length=100, unique=True),
        ),
    ]
