# Generated by Django 5.0.4 on 2024-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvs_app', '0007_applicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinteractionlog',
            name='username',
            field=models.CharField(default='anonymous', max_length=150),
        ),
        migrations.AlterField(
            model_name='clientinteractionlog',
            name='client_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
