# Generated by Django 5.0.4 on 2024-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvs_app', '0008_clientinteractionlog_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinteractionlog',
            name='server_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clientinteractionlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientinteractionlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
